"""Type stub for the compiled Rust inline core (``simplipy._core``).

Hand-written to mirror the ``#[pymethods]`` surface in ``rust/lib.rs``; keep in sync on changes.
Compiled extensions are opaque to static type-checkers, so this stub is what makes the ``Engine``
surface (and the module constants) visible to mypy/pyright downstream and in this package.
"""
from typing import Literal

__build__: str

class Engine:
    @staticmethod
    def from_paths(config_yaml_path: str, rules_json_path: str) -> Engine: ...
    @property
    def engine_id(self) -> str: ...
    def simplify(
        self,
        tokens: list[str],
        node_budget: int = ...,
        max_pattern_length: int | None = ...,
        apply_simplification_rules: bool = ...,
        wildcard_all: bool = ...,
    ) -> list[str]: ...
    def mask(self, tokens: list[str]) -> list[str]: ...
    def apply_rules(
        self, tokens: list[str], max_pattern_length: int | None = ...
    ) -> list[str]: ...
    def cancel_only(self, tokens: list[str]) -> list[str]: ...
    def sort_only(self, tokens: list[str]) -> list[str]: ...
    def is_valid(self, tokens: list[str]) -> bool: ...
    def prefix_to_infix(
        self, tokens: list[str], power: Literal["func", "**"] = ..., realization: bool = ...
    ) -> str: ...
    def infix_to_prefix(self, infix_expression: str) -> list[str]: ...
    def convert_expression(self, prefix_expr: list[str]) -> list[str]: ...
    def parse(
        self, infix_expression: str, convert_expression: bool = ..., mask_numbers: bool = ...
    ) -> list[str]: ...
    def operators_to_realizations(self, tokens: list[str]) -> list[str]: ...
    def realizations_to_operators(self, tokens: list[str]) -> list[str]: ...
    def evaluate_constant_subtree(self, tokens: list[str]) -> str | None: ...
    @staticmethod
    def py_float_repr(x: float) -> str: ...
