# Non-source trees must never be rewritten by a formatting hook -- flake8 and mypy
# already exclude them; this makes that global.
exclude: ^remine/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
        - id: flake8
          additional_dependencies: [ Flake8-pyproject ]
          exclude: ^(experimental/|benchmarks/|remine/|src/simplipy/verify/)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        additional_dependencies: [
            types-setuptools==80.9.0.20250529,
            types-tqdm==4.67.0.20250516 ,
            types-PyYAML==6.0.12.20250516]
        exclude: ^(tests/|experimental/|benchmarks/|remine/|src/simplipy/promotion/|src/simplipy/verify/)
