# Project information
site_name: SimpliPy
site_author: Paul Saegert
repo_url: https://github.com/psaegert/simplipy
repo_name: psaegert/simplipy
edit_uri: blob/main/

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.instant
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight

# Extensions for better rendering
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

nav:
  - API-Reference: api.md

# Plugin configurations
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            merge_init_into_class: True
            show_bases: false
            heading_level: 2 # This is a global default
            docstring_section_style: spacy
            show_signature_annotations: true
            separate_signature: true
            show_root_heading: false
            members_order: source
            show_source: true
