extra_internal_terms: [
  '<constant>',
  '0',
  '1',
  '(-1)',
  'np.pi',
  'np.e',
  'float("inf")',
  'float("-inf")',
  'float("nan")'
]

dummy_variables: null  # Determine automatically based on max source pattern length

max_source_pattern_length: 3
max_target_pattern_length: 2

n_samples: 1024
n_constants: 1024

constants_fit_challenges: 16
constants_fit_retries: 16  # per challenge