operators:
  "+":
    realization: "+"
    alias: ["add", "plus"]
    inverse: "-"
    arity: 2
    weight: 10
    precedence: 1
    commutative: true
    symmetry: 0
    positive: false
    monotonicity: 0
  "-":
    realization: "-"
    alias: ["sub", "minus"]
    inverse: "+"
    arity: 2
    weight: 5
    precedence: 1
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 0
  neg:
    realization: "nsrops.neg"
    alias: ["negative"]
    inverse: "neg"
    arity: 1
    weight: 5
    precedence: 2.5
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: -1
  "*":
    realization: "*"
    alias: ["mul", "times"]
    inverse: "/"
    arity: 2
    weight: 10
    precedence: 2
    commutative: true
    symmetry: 0
    positive: false
    monotonicity: 0
  "/":
    realization: "nsrops.div"
    alias: ["div", "divide"]
    inverse: "*"
    arity: 2
    weight: 5
    precedence: 2
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 0
  abs:
    realization: "abs"
    alias: ["absolute"]
    inverse: null
    arity: 1
    weight: 4
    precedence: 3
    commutative: false
    symmetry: 1 # symmetric
    positive: true
    monotonicity: 0
  inv:
    realization: "nsrops.inv"
    alias: ["inverse"]
    inverse: "inv"
    arity: 1
    weight: 4
    precedence: 4
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: -1
  pow2:
    realization: "nsrops.pow2"
    alias: ["square"]
    inverse: null
    arity: 1
    weight: 4
    precedence: 3
    commutative: false
    symmetry: 1 # symmetric
    positive: true
    monotonicity: 0
  pow3:
    realization: "nsrops.pow3"
    alias: ["cube"]
    inverse: "pow1_3"
    arity: 1
    weight: 2
    precedence: 3
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 1
  pow4:
    realization: "nsrops.pow4"
    alias: []
    inverse: null
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 1
    positive: true
    monotonicity: 0
  pow5:
    realization: "nsrops.pow5"
    alias: []
    inverse: "pow1_5"
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 1
  pow1_2:
    realization: "nsrops.pow1_2"
    alias: ["sqrt"]
    inverse: null
    arity: 1
    weight: 4
    precedence: 3
    commutative: false
    symmetry: 0
    positive: true
    monotonicity: 1
  pow1_3:
    realization: "nsrops.pow1_3"
    alias: []
    inverse: null
    arity: 1
    weight: 2
    precedence: 3
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 1
  pow1_4:
    realization: "nsrops.pow1_4"
    alias: []
    inverse: null
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: true
    monotonicity: 1
  pow1_5:
    realization: "nsrops.pow1_5"
    alias: []
    inverse: null
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 1
  sin:
    realization: "numpy.sin"
    alias: []
    inverse: "asin"
    arity: 1
    weight: 4
    precedence: 2
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 0
  cos:
    realization: "numpy.cos"
    alias: []
    inverse: "acos"
    arity: 1
    weight: 4
    precedence: 2
    commutative: false
    symmetry: 1 # symmetric
    positive: false
    monotonicity: 0
  tan:
    realization: "numpy.tan"
    alias: []
    inverse: "atan"
    arity: 1
    weight: 4
    precedence: 2
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 0
  asin:
    realization: "numpy.arcsin"
    alias: ["arcsin"]
    inverse: "sin"
    arity: 1
    weight: 2
    precedence: 2
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 1
  acos:
    realization: "numpy.arccos"
    alias: ["arccos"]
    inverse: "cos"
    arity: 1
    weight: 2
    precedence: 2
    commutative: false
    symmetry: 0
    positive: true
    monotonicity: 1
  atan:
    realization: "numpy.arctan"
    alias: ["arctan"]
    inverse: "tan"
    arity: 1
    weight: 2
    precedence: 2
    commutative: false
    symmetry: -1 # anti-symmetric
    positive: false
    monotonicity: 1
  exp:
    realization: "numpy.exp"
    alias: []
    inverse: "log"
    arity: 1
    weight: 4
    precedence: 3
    commutative: false
    symmetry: 0
    positive: true
    monotonicity: 1
  log:
    realization: "numpy.log"
    alias: ["ln"]
    inverse: "exp"
    arity: 1
    weight: 4
    precedence: 2
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  mult2:
    realization: "nsrops.mult2"
    alias: []
    inverse: div2
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  mult3:
    realization: "nsrops.mult3"
    alias: []
    inverse: div3
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  mult4:
    realization: "nsrops.mult4"
    alias: []
    inverse: div4
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  mult5:
    realization: "nsrops.mult5"
    alias: []
    inverse: div5
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  div2:
    realization: "nsrops.div2"
    alias: []
    inverse: mult2
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  div3:
    realization: "nsrops.div3"
    alias: []
    inverse: mult3
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  div4:
    realization: "nsrops.div4"
    alias: []
    inverse: mult4
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1
  div5:
    realization: "nsrops.div5"
    alias: []
    inverse: mult5
    arity: 1
    weight: 1
    precedence: 3
    commutative: false
    symmetry: 0
    positive: false
    monotonicity: 1

variables: 3

simplification_kwargs:
  rules_file: "{{ROOT}}/data/rules/dev.json"
  extra_internal_terms: [
    '<num>',
    '0',
    '1',
    '2',
    '(-1)',
    '(-2)',
    'float("inf")',
    'float("-inf")',
    'float("nan")'
  ]