operators:
  "+":
    realization: "+"
    alias: []
    inverse: "-"
    arity: 2
    precedence: 1
    commutative: true
  "-":
    realization: "-"
    alias: []
    inverse: "+"
    arity: 2
    precedence: 1
    commutative: false
  neg:
    realization: "simplipy.operators.neg"
    alias: []
    inverse: "neg"
    arity: 1
    precedence: 2.5
    commutative: false
  "*":
    realization: "*"
    alias: []
    inverse: "/"
    arity: 2
    precedence: 2
    commutative: true
  "/":
    realization: "simplipy.operators.div"
    alias: []
    inverse: "*"
    arity: 2
    precedence: 2
    commutative: false
  abs:
    realization: "abs"
    alias: []
    inverse: null
    arity: 1
    precedence: 3
    commutative: false
  inv:
    realization: "simplipy.operators.inv"
    alias: ["inverse"]
    inverse: "inv"
    arity: 1
    precedence: 4
    commutative: false
  pow2:
    realization: "simplipy.operators.pow2"
    alias: ["square"]
    inverse: null
    arity: 1
    precedence: 3
    commutative: false
  pow3:
    realization: "simplipy.operators.pow3"
    alias: ["cube"]
    inverse: "pow1_3"
    arity: 1
    precedence: 3
    commutative: false
  pow4:
    realization: "simplipy.operators.pow4"
    alias: []
    inverse: null
    arity: 1
    precedence: 3
    commutative: false
  pow5:
    realization: "simplipy.operators.pow5"
    alias: []
    inverse: "pow1_5"
    arity: 1
    precedence: 3
    commutative: false
  pow1_2:
    realization: "simplipy.operators.pow1_2"
    alias: ["sqrt"]
    inverse: null
    arity: 1
    precedence: 3
    commutative: false
  pow1_3:
    realization: "simplipy.operators.pow1_3"
    alias: []
    inverse: null
    arity: 1
    precedence: 3
    commutative: false
  pow1_4:
    realization: "simplipy.operators.pow1_4"
    alias: []
    inverse: null
    arity: 1
    precedence: 3
    commutative: false
  pow1_5:
    realization: "simplipy.operators.pow1_5"
    alias: []
    inverse: null
    arity: 1
    precedence: 3
    commutative: false
  sin:
    realization: "numpy.sin"
    alias: []
    inverse: "asin"
    arity: 1
    precedence: 2
    commutative: false
  cos:
    realization: "numpy.cos"
    alias: []
    inverse: "acos"
    arity: 1
    precedence: 2
    commutative: false
  tan:
    realization: "numpy.tan"
    alias: []
    inverse: "atan"
    arity: 1
    precedence: 2
    commutative: false
  asin:
    realization: "numpy.arcsin"
    alias: ["arcsin"]
    inverse: "sin"
    arity: 1
    precedence: 2
    commutative: false
  acos:
    realization: "numpy.arccos"
    alias: ["arccos"]
    inverse: "cos"
    arity: 1
    precedence: 2
    commutative: false
  atan:
    realization: "numpy.arctan"
    alias: ["arctan"]
    inverse: "tan"
    arity: 1
    precedence: 2
    commutative: false
  exp:
    realization: "numpy.exp"
    alias: []
    inverse: "log"
    arity: 1
    precedence: 3
    commutative: false
  log:
    realization: "numpy.log"
    alias: ["ln"]
    inverse: "exp"
    arity: 1
    precedence: 2
    commutative: false
  mult2:
    realization: "simplipy.operators.mult2"
    alias: []
    inverse: div2
    arity: 1
    precedence: 3
    commutative: false
  mult3:
    realization: "simplipy.operators.mult3"
    alias: []
    inverse: div3
    arity: 1
    precedence: 3
    commutative: false
  mult4:
    realization: "simplipy.operators.mult4"
    alias: []
    inverse: div4
    arity: 1
    precedence: 3
    commutative: false
  mult5:
    realization: "simplipy.operators.mult5"
    alias: []
    inverse: div5
    arity: 1
    precedence: 3
    commutative: false
  div2:
    realization: "simplipy.operators.div2"
    alias: []
    inverse: mult2
    arity: 1
    precedence: 3
    commutative: false
  div3:
    realization: "simplipy.operators.div3"
    alias: []
    inverse: mult3
    arity: 1
    precedence: 3
    commutative: false
  div4:
    realization: "simplipy.operators.div4"
    alias: []
    inverse: mult4
    arity: 1
    precedence: 3
    commutative: false
  div5:
    realization: "simplipy.operators.div5"
    alias: []
    inverse: mult5
    arity: 1
    precedence: 3
    commutative: false

rules: "{{ROOT}}/data/rules/dev.json"
