on:
  push:
    branches: main
  pull_request:

name: pytest

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with LFS files
      - uses: actions/checkout@v4.2.2
        with:
          lfs: true

      # Setup Python
      - name: Setup Python 3.12
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"

      # Install the package and development requirements
      - name: Install package and development requirements
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Run the tests
      - name: Run tests
        run: |
          pytest tests
